spring.application.name=gms

spring.datasource.url=jdbc:postgresql://localhost:5432/gms?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate properties

# Hibernate uses this dialect to internally generate sql queries
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# "update" is used to create automatically tables if they not exist, and update them if they exist
spring.jpa.hibernate.ddl-auto=update
